-- Sphere Studio capture backend
-- Run this once in Supabase Dashboard -> SQL Editor.
-- Safe to re-run.

create table if not exists public.capture_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  consented_at timestamptz,
  consent_version text,
  mode text not null default 'auto' check (mode in ('auto','manual')),
  status text not null default 'capturing' check (status in ('capturing','completed','abandoned')),
  total_shots integer not null default 0 check (total_shots between 0 and 38),
  low_quality_count integer not null default 0,
  completed_at timestamptz
);

create table if not exists public.capture_frames (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.capture_sessions(id) on delete cascade,
  user_id uuid not null default auth.uid(),
  shot_index integer not null check (shot_index between 1 and 38),
  row_label text not null,
  mode text not null check (mode in ('auto','manual')),
  sharpness double precision,
  width integer,
  height integer,
  storage_path text not null,
  created_at timestamptz not null default now(),
  unique(session_id, shot_index)
);

alter table public.capture_sessions enable row level security;
alter table public.capture_frames enable row level security;

drop policy if exists "capture_sessions_insert_own" on public.capture_sessions;
create policy "capture_sessions_insert_own"
on public.capture_sessions for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "capture_sessions_select_own" on public.capture_sessions;
create policy "capture_sessions_select_own"
on public.capture_sessions for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "capture_sessions_update_own" on public.capture_sessions;
create policy "capture_sessions_update_own"
on public.capture_sessions for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "capture_frames_insert_own" on public.capture_frames;
create policy "capture_frames_insert_own"
on public.capture_frames for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "capture_frames_select_own" on public.capture_frames;
create policy "capture_frames_select_own"
on public.capture_frames for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "capture_frames_update_own" on public.capture_frames;
create policy "capture_frames_update_own"
on public.capture_frames for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('capture-photos', 'capture-photos', false)
on conflict (id) do update set public = false;

drop policy if exists "capture_photos_insert_own" on storage.objects;
create policy "capture_photos_insert_own"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'capture-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "capture_photos_select_own" on storage.objects;
create policy "capture_photos_select_own"
on storage.objects for select
to authenticated
using (
  bucket_id = 'capture-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "capture_photos_update_own" on storage.objects;
create policy "capture_photos_update_own"
on storage.objects for update
to authenticated
using (
  bucket_id = 'capture-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'capture-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "capture_photos_delete_own" on storage.objects;
create policy "capture_photos_delete_own"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'capture-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create index if not exists capture_sessions_created_at_idx on public.capture_sessions(created_at desc);
create index if not exists capture_frames_session_idx on public.capture_frames(session_id, shot_index);


-- Explicit API privileges for anonymous-authenticated capture users.
grant select, insert, update, delete on public.capture_sessions to authenticated;
grant select, insert, update, delete on public.capture_frames to authenticated;

do $$
begin
  if exists (
    select 1 from pg_class c
    join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relname='capture_frames_id_seq'
  ) then
    grant usage, select on sequence public.capture_frames_id_seq to authenticated;
  end if;
end $$;
